# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: gcc:8

# https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html

# maximum amount of minutes a step can execute at a global level or at a step level
options:
  max-time: 10

# shallow clone
clone:
  depth: 3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install -y cmake
          - git submodule update --init --remote
          - g++ --version
          - mkdir build
          - cd build
          - cmake -DTWINS_USE_SANITIZERS=OFF -DTWINS_BUILD_UT=ON ..
          - make -j4
          - ctest -V
          - apt-get install -y python-pip
          - pip install cpp-coveralls gcovr
          #- coveralls -b . -r .. -i "lib" -E ".*/lib/tests/.*" -t xyTXxJUFndVGPY153wKb3aLwb8P71CAwr
          - coveralls -b . -r .. -i "lib/src" -i "lib/inc" -t xyTXxJUFndVGPY153wKb3aLwb8P71CAwr

